services:
  - type: web
    name: telegram-bot-daily-message
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: CHAT_ID
        value: your_chat_id_here
      - key: VIDEO_URL
        value: your_video_url_here
      - key: MESSAGE_TEXT
        value: your_message_text_here
